version: "3.9"
services:
  backend:
    container_name: backend
    build: ./backend
    ports:
      - "3000:3000"
    depends_on:
      - redis
    env_file:
      - ./backend/.env

  frontend:
    container_name: frontend
    build: ./frontend
    ports:
      - "3001:3000"
    env_file:
      - ./frontend/.env.local

  notifier:
    container_name: notifier
    build: ./notifier
    ports:
      - "8000:8000"
    depends_on:
      - redis

  redis:
    container_name: redis
    image: redis:7
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

volumes:
  redis_data:
